testcase_sources: "https://github.com/katalon-studio-samples/ci-samples.git"

# if using docker images katalonstudio/katalon if specific the API key in katalon command
data:
  entrypoint.sh: |-
    #!/bin/bash
    katalonc.sh -projectPath=/workspace -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest"

image:
  repository: katalonstudio/katalon
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  annotations: {}
  name: katalonstudio

  namespace: katalon