apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "katalonstudio.fullname" . }}
  labels:
    name: {{ include "katalonstudio.fullname" . }}
    app: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec: 
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image:  "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          command:
            - /bin/entrypoint.sh
          volumeMounts:
          - name: configmap-volume
            mountPath: /bin/entrypoint.sh
            readOnly: true
            subPath: entrypoint.sh
          - name: source
            mountPath: /workspace
      restartPolicy: OnFailure
      volumes:
        - name: configmap-volume
          configMap:
            defaultMode: 0700
            name: {{ include "katalonstudio.fullname" . }}-configmap
        - name: source
          emptyDir: {}  
      initContainers:
        - name: download
          image: alpine:3.7
          command: ["/bin/sh","-c"]
          args: ['apk add --no-cache git && git clone {{ .Values.testcase_sources }} /tmp/']
          volumeMounts:
            - mountPath: /tmp/
              name:  source